import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ProviderComponent from "@/lib/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Groww",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderComponent>
          <div>
            <Navbar />
            {children}
          </div>
        </ProviderComponent>
      </body>
    </html>
  );
}
